[MM-30403] Expand users mentioned in post
mattermost/mattermost-plugin-apps pull request #127
Opened 2021-04-01 12:50 UTC by iomodo

#### Summary
This PR adds support of the mentioned user expand.

#### Ticket Link

  Fixes https://mattermost.atlassian.net/browse/MM-30403

2021-04-01 16:36 UTC, levb requested changes
As discussed on the call, the primary focus should be providing the expand map for the Call Values; whether or not we need it on the Post is TBD, maybe as a separate "Expand" clause?

2021-04-12 13:32 UTC, larkox requested changes

2021-04-12 13:32 UTC, larkox commented on server/proxy/mention.go
> +func getMentionsEnabledFields(post *model.Post) model.StringArray {
Should we consider also Embedded bindings?

2021-04-12 13:32 UTC, larkox commented on server/proxy/mention.go
> +			user, nErr := e.mm.User.GetByUsername(mention)
Are we using the plugin client to get the users? Any chance this may be exposing users to users with not enough permissions? (e.g. guest users).

2021-05-03 14:53 UTC, justinegeffen commented
@iomodo, would you be open to updating the docs with these changes? They can be found here: https://github.com/mattermost/mattermost-developer-documentation/tree/master/site/content/integrate/apps.

2021-05-19 08:07 UTC, larkox requested changes
My previous comments still apply

2021-09-30 18:12 UTC, hanzei commented
Closing this PR for now

2021-09-30 18:12 UTC, closed without merging