Add headers for static assets
mattermost/mattermost-plugin-apps pull request #136
Opened 2021-04-07 18:09 UTC by iomodo

#### Summary
This PR adds headers to the static assets

#### Ticket Link

  Fixes https://mattermost.atlassian.net/browse/MM-34648

2021-04-08 09:22 UTC, larkox approved these changes

2021-04-08 09:38 UTC, larkox commented
I am not savvy enough about this, but I wonder if there is any header that may become "dangerous" that we want to filter out.

2021-04-12 12:14 UTC, hanzei requested changes
I'm with @larkox here. Copying all headers might have side effects that we don't know about. We should have an allow list instead.

2021-04-15 07:41 UTC, hanzei approved these changes

2021-04-15 09:58 UTC, merged