[MM-34982] Add Zendesk 0.2.0 to manifest list
mattermost/mattermost-plugin-apps pull request #167
Opened 2021-04-27 13:48 UTC by hanzei

#### Summary
Add Zendesk 0.2.0 to manifest list

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-34982

2021-04-27 13:48 UTC, hanzei commented
@DHaussermann Please let me know if Zendesk will be in 5.29 once you tested it.

2021-04-27 23:21 UTC, catalintomai approved these changes

2021-04-29 14:47 UTC, jfrerich commented
We are actually going to release v0.2.1.

Zendesk PR is here -> https://github.com/mattermost/mattermost-app-zendesk/pull/46

2021-04-29 14:50 UTC, jfrerich requested changes
As discussed in the meeting this morning, the plan is to release `v0.2.1`

2021-04-29 18:00 UTC, jfrerich approved these changes

2021-04-29 21:32 UTC, merged