Move examples to mattermost-example-apps
mattermost/mattermost-plugin-apps pull request #362
Opened 2022-08-31 17:24 UTC by azigler

_New version of #357 based on #336_ 
 
**This PR should not be merged until https://github.com/mattermost/mattermost-developer-documentation/pull/1106 is merged.**

Fixes:
- https://github.com/mattermost/mattermost-plugin-apps/issues/330
- https://github.com/mattermost/mattermost-plugin-apps/issues/329
- https://github.com/mattermost/mattermost-plugin-apps/issues/300

Updates:
- `README` points to developer resources and guides

This PR moves:
- the content from `/examples` to the new https://github.com/mattermost/mattermost-app-examples repository.
- the `/dev` environment to the new https://github.com/mattermost/mattermost-app-examples repository
- the new content from merged PR https://github.com/mattermost/mattermost-plugin-apps/pull/352 to correspond with the new Python quick start guide in https://github.com/mattermost/mattermost-developer-documentation/pull/1106.

`/examples/goapp` has been preserved in this repository as `/goapp`.

2022-08-31 17:25 UTC, azigler commented
@mickmister @levb Was simpler to make a new PR from latest master. Thanks y'all!

2022-09-01 16:06 UTC, levb requested changes
2 high-level comments:

1. The E2E (Cypress) tests depend on the hello-world app, so will be broken by this PR.

I suggest that we fix the E2E test (it's currently broken with the `master` webapp) and make it use the test app `/test/app` instead of hello.

2. As I understand, this PR creates a `/goapp` directory for the goapp examples. 3/5 that's either wrong, or we should move the `goapp` implementation there (currently in `/apps/goapp`) and have a `./examples` underneath.

2022-09-02 14:05 UTC, mickmister commented
> 2. As I understand, this PR creates a `/goapp` directory for the goapp examples. 3/5 that's either wrong, or we should move the `goapp` implementation there (currently in `/apps/goapp`) and have a `./examples` underneath.

@levb When you say "this PR", do you mean this PR we're commenting on? The PR mostly removing things, and doesn't add/move any files. 1/5 I'm thinking we should have the `goapp` tooling in the Apps repo, and have an example implementation using it in the examples repo.

2022-09-02 14:06 UTC, mickmister reviewed
I see one typo in the copy changes, otherwise LGTM :+1:

Holding off on approving due to pending concerns from Lev

2022-09-02 14:06 UTC, mickmister commented on README.md
> +Refer to the [Mattermost Apps Quick Start Guide](https://developers.mattermost.com/integrate/apps/quickstart/) for instructions on how to use the development environment and examples in the [mattermo
```suggestion
Refer to the [Mattermost Apps Quick Start Guide](https://developers.mattermost.com/integrate/apps/quickstart/) for instructions on how to use the development environment and examples in the [mattermost/mattermost-app-examples](https://github.com/mattermost/mattermost-app-examples) repository.
```

2022-10-10 17:58 UTC, levb commented
@azigler fix lint, please?

2022-10-13 18:28 UTC, mickmister commented
@levb This is good to merge now. Note that I temporarily put `examples/go/hello-world` in `test/hello-world` to make the e2e tests work. Do you think the test is still necessary?

2022-10-13 18:28 UTC, mickmister commented
@levb I'd like you opinion on the above question before merging. cc @hanzei

2022-10-13 19:26 UTC, levb commented
@mickmister 3/5 we should be using the test app for the E2E test and not hello. If you could make the change, I'd MUCH appreciate it.

2022-10-14 17:07 UTC, mickmister commented
> @mickmister 3/5 we should be using the test app for the E2E test and not hello. If you could make the change, I'd MUCH appreciate it.

@levb Mind if I tackle this while taking care of the e2e webapp master branch issue? It seems out of scope of this PR

2022-10-14 17:25 UTC, merged

2022-10-14 17:51 UTC, azigler commented
Thank you @mickmister and @levb!

2022-10-14 18:05 UTC, levb commented
@mickmister @azigler then I'd argue don't bother with leaving hello-world since the test is broken ATM anyway; it doesn't even get to the point of deploying the app.