[MM-50056] Rejects manifests with empty DisplayName
mattermost/mattermost-plugin-apps pull request #439
Opened 2023-01-30 13:18 UTC by hanzei

#### Summary
The install process later fails with `failed to create OAuth2 App: OAuthApp.IsValid: Invalid name`  if they displayName is empty. It should fail sooner and warn about the empty display name.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-50056

2023-01-30 16:23 UTC, javaguirre approved these changes

2023-01-30 16:24 UTC, levb approved these changes

2023-01-30 16:29 UTC, javaguirre requested changes
I think it would be good to have a specific test where the DisplayName fails, since we are saying it should "fail" in the tests, but it could be failing because of a different reason, WDYT?

Sorry I changed my review, but It tickled me after.

This will require to refactor manifest testing a bit.

2023-01-31 09:28 UTC, hanzei commented
That's a good suggestion @javaguirre Updated the tests in [`7a549ae` (#439)](https://github.com/mattermost/mattermost-plugin-apps/pull/439/commits/7a549aec328bd8ea5006b778b498a6031244a11a)

2023-01-31 11:36 UTC, javaguirre approved these changes

2023-01-31 11:42 UTC, merged