Logging improvement
mattermost/mattermost-plugin-apps pull request #456
Opened 2023-02-07 23:02 UTC by levb

#### Summary
Some timing and details

#### Ticket Link
None

2023-02-07 23:11 UTC, mickmister requested changes
LGTM other than one typo

2023-02-07 23:11 UTC, mickmister commented on server/httpin/service.go
> +		if s.Config.Get().DeveloperMode {
```suggestion
	if s.Config.Get().DeveloperMode {
```

2023-02-08 00:14 UTC, mickmister approved these changes

2023-02-17 06:28 UTC, hanzei requested changes
Neat. I quite like the poor mans monitoring here.

2023-02-17 06:28 UTC, hanzei commented on server/proxy/enable.go
> +			log.With("message", message).Infof("Enabled app %s", appID)
```suggestion
			r.Log.With("message", message).Infof("Enabled app %s", appID)
```

2023-02-17 06:28 UTC, hanzei commented on server/proxy/bindings.go
> +			log.Errorf("GetBindings: %v", err)
```suggestion
			log.WithError(err),Errorf("GetBindings: failed")
```

2023-02-17 06:28 UTC, hanzei commented on server/proxy/bindings.go
> +			log.Errorf("GetBindings: %v", err)
Should this really be logged on  `Error`?

2023-02-17 06:58 UTC, hanzei commented on server/proxy/bindings.go
> +		log := r.Log.With("elapsed", time.Since(start).String)
```suggestion
		log := r.Log.With("elapsed", time.Since(start).String())
```

2023-02-18 14:54 UTC, levb commented on server/httpin/service.go
> -	)
URL and path both - seem redundant

2023-02-18 17:33 UTC, hanzei commented on server/httpin/service.go
> -	)
Well, for production we don't log the URL. And having at least something, the path, in the logs is quite helpful.

Also, the path is way easier to read then the full URL.

2023-02-19 12:51 UTC, levb commented on server/proxy/invoke_call.go
> +			log.Errorf("Call failed: %v", err)
Why? an error prints .Error() on %v...

2023-02-19 12:53 UTC, levb commented on server/proxy/install.go
> +			r.Log.Infof(message)
why? `log` has the elapsed field set

2023-02-19 12:55 UTC, levb commented on server/proxy/enable.go
> +			log.With("message", message).Infof("Enabled app %s", appID)
why? `log` has elapsed time.

2023-02-19 20:31 UTC, hanzei approved these changes

2023-02-19 20:31 UTC, hanzei commented on server/proxy/invoke_call.go
> +			log.Debugf("Called %s:%s -> %s", app.AppID, creq.Path, cresp.Type)
Filled https://mattermost.atlassian.net/browse/MM-50703

2023-02-19 20:32 UTC, merged