Remove reference to prod rudder key in ci workflow, keep in cd workflow
mattermost/mattermost-plugin-apps pull request #470
Opened 2023-04-03 18:47 UTC by mickmister

#### Summary

Using the prod Rudderstack telemetry key in CI can skew our telemetry numbers. The production builds of the plugin produced by the `cd.yml` should still contain the prod key. This PR We makes it so we use the development key instead for the `ci.yml` workflow.

## Ticket Link

Fixes https://github.com/mattermost/mattermost-plugin-apps/issues/469

2023-04-04 07:33 UTC, trilopin approved these changes
Nice!

2023-04-04 08:51 UTC, toninis approved these changes
👍🏼

2023-04-04 09:32 UTC, toninis requested changes
You need to add the environmental variable on the CD pipeline from the secrets in order to accessible . 
It is not accessible by default 
```yaml
env:
  MM_RUDDER_PLUGINS_PROD:  ${{ secrets.MM_RUDDER_PLUGINS_PROD }}
```

Since with https://github.com/mattermost/mattermost-plugin-apps/pull/468 you expect it to exist

2023-04-04 13:14 UTC, toninis approved these changes

2023-04-11 10:11 UTC, hanzei approved these changes

2023-04-11 20:31 UTC, merged